---
title: ""
---

&nbsp;

### **Financial Data Analysis and Visualization in Python**

Welcome to the course website for FM 5990 - Spring 2019.

&nbsp;

```{r, loading_packages, include=FALSE}
library(fOptions)
library(bizdays)
library(tidyverse)
library(gridExtra)
```



```{r, services_art, echo=FALSE, fig.height=3.25, fig.width=8, fig.align="center"}
df_market_history <- 
    read_csv("practice_market_history.csv", col_types = cols())

df_liquidity <-
  df_market_history %>% 
    group_by(underlying) %>% 
    summarize(daily_volume = (sum(volume) / nrow(df_market_history %>% distinct(trade_date)))
              ,avg_spread = mean(ask - bid)) %>% 
    arrange(desc(daily_volume))


# let's reproduce this graph using ggplot()
p1 <- 
  ggplot(data = df_liquidity) +
  geom_point(mapping = aes(x = log(daily_volume), y = avg_spread, color="grey37"), size = 0.75, na.rm = TRUE) +
  geom_smooth(mapping = aes(x = log(daily_volume), y = avg_spread), color="steelblue1", se = FALSE, method = "loess", na.rm = TRUE) +
  scale_y_continuous(limits = c(0, 0.2)) +
  theme(axis.title.x=element_blank()
        , axis.text.x=element_blank()
        , axis.ticks.x=element_blank()
        , axis.title.y=element_blank()
        , axis.text.y=element_blank()
        , axis.ticks.y=element_blank()
        , legend.position="none"
  )


df_spy_time <-
  df_market_history %>% 
    filter(underlying == "SPY") %>%
    filter(expiration == as.Date("2013-09-21")) %>% 
    arrange(trade_date, strike)


# log-strike, like a boss
p2 <- 
    ggplot(data = df_spy_time %>% filter(trade_date < as.Date("2013-09-01"))) +
    geom_line(
        mapping = aes(x = log(strike/implied_forward)
        , y = implied_vol, group = trade_date, color = trade_date)
        , size = 0.75
        , alpha = 0.65
    ) +
  theme(axis.title.x=element_blank()
        , axis.text.x=element_blank()
        , axis.ticks.x=element_blank()
        , axis.title.y=element_blank()
        , axis.text.y=element_blank()
        , axis.ticks.y=element_blank()
        , legend.position="none"
  )

gridExtra::grid.arrange(suppressWarnings(p1), p2, nrow = 1)
```


```{r, greeks_by_moniness, echo=FALSE, out.width="67%", fig.align="center"}

# type = "c"
# upx = seq(90, 110, 1)
# strike = 100
# time = 21/252
# rf = 0.01
# div = 0
# vol = 0.25
# 
# option_values <-
#   GBSCharacteristics(
#     TypeFlag = type
#     , S = upx
#     , X = strike
#     , Time = time
#     , r = rf
#     , b = div
#     , sigma = vol
#   )
# 
# 
# graph_values <-
#   tibble(
#     upx = upx
#     , intrinsic = map_dbl(upx, function(x) max(x - strike, 0))
#     , px = option_values$premium
#     , delta = option_values$delta
#     , vega = option_values$vega / 100
#     , theta = option_values$theta / 252
#   )
# 
# 
# p1 <-
# ggplot(data = graph_values ) +
#   geom_line(aes(x = upx, y = intrinsic), size = 0.75, alpha = 0.65) +
#   geom_line(aes(x = upx, y = px - intrinsic), color = "green4", size = 1.0, alpha = 0.75) +
#   geom_vline(xintercept = 100, color = "red", lty = "dashed") +
#   theme(axis.title.x=element_blank()
#         , axis.text.x=element_blank()
#         , axis.ticks.x=element_blank()
#         , axis.title.y=element_blank()
#         , axis.text.y=element_blank()
#         , axis.ticks.y=element_blank()
#   ) +
#   labs(
#        x = ""
#        ,y = ""
#   ) +
#   annotate("text", label = "extrinsic" , x = 92, y = 9.65, size = 4, colour = "grey37")
# 
# p2 <-
# ggplot(data = graph_values ) +
#   geom_line(aes(x = upx, y = delta), color = "blue", size = 1.0, alpha = 0.6) +
#   geom_vline(xintercept = 100, color = "red", lty = "dashed") +
#   theme(axis.title.x=element_blank()
#     , axis.text.x=element_blank()
#     , axis.ticks.x=element_blank()
#     , axis.title.y=element_blank()
#     , axis.text.y=element_blank()
#     , axis.ticks.y=element_blank()
#   ) +
#   labs(
#        x = ""
#        , y = ""
#   ) +
#   annotate("text", label = "delta" , x = 91.5, y = 0.875, size = 4, colour = "grey37")
# 
# 
# p3 <-
# ggplot(data = graph_values ) +
#   geom_line(aes(x = upx, y = vega), color = "orange", size = 1.0, alpha = 0.7) +
#   geom_vline(xintercept = 100, color = "red", lty = "dashed") +
#   theme(axis.title.x=element_blank()
#     , axis.text.x=element_blank()
#     , axis.ticks.x=element_blank()
#     , axis.title.y=element_blank()
#     , axis.text.y=element_blank()
#     , axis.ticks.y=element_blank()
#   ) +
#   labs(
#        x = ""
#        , y = ""
#   ) +
#   annotate("text", label = "vega" , x = 91.5, y = .11, size = 4, colour = "grey37")
# 
# p4 <-
# ggplot(data = graph_values ) +
#   geom_line(aes(x = upx, y = theta), color = "pink", size = 1.0) +
#   geom_vline(xintercept = 100, color = "red", lty = "dashed") +
#   theme(axis.title.x=element_blank()
#     , axis.text.x=element_blank()
#     , axis.ticks.x=element_blank()
#     , axis.title.y=element_blank()
#     , axis.text.y=element_blank()
#     , axis.ticks.y=element_blank()
#   ) +
#   labs(
#        x = ""
#        , y = ""
#   ) +
#   annotate("text", label = "theta" , x = 93, y = -0.025, size = 4, colour = "grey37")
# 
# 
# 
# gridExtra::grid.arrange(p1, p2, p3, p4
#                         , nrow = 2)
#                         #, top = "Greeks vs Underlying Price")
```