---
title: ""
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

### **Weekly Plan**

This page will serve as a more detailed plan for weeks to come, and also a record what was covered in previous weeks.

&nbsp;


#### (01) 01/22 - preliminaries

<span style="color:gray":>*Material Covered:*</span> 

**Topics:** administrative housekeeping, syllabus, installing Anaconda distribution, introductory remarks about python, lists, dicts, numpy arrays, dataframes, operations on dataframe columns, aggregating calculations on dataframe columns

**Slides:** 01_housekeeping; 02_python_intro

**Tutorials:** 01_jupyter_intro, 02_python_basics, 03_numpy_pandas_intro

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 01_volume_weighted_average_price

**Required Reading:** PDSH 2.1-2.7; PDSH 3.1-3.3; WTP 7-8

**Supplemental Reading:** LOD - Options 101


&nbsp;

#### (02) 01/29 - **cancelled**


&nbsp;

#### (03) 02/05 - intro to `pandas` and `numpy`


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** how to use the texts for the course, numpy arrays, pandas dataframes, indexing, slicing, masking

**Slides:** 03_guide_to_programming_book

**Tutorials:** 03_numpy_pandas_intro, 04_dataframe_indexing_slicing, 05_dataframe_masking

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 02_option_price_intro

**Required Reading:** PDSH 3.8; WTP 9

**Supplemental Reading:** None

&nbsp;


#### (04) 02/12 - functions, iteration, aggregation


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** if-else, iteration, calculating returns, writing functions, calculating option payoffs, aggregation and grouping

**Slides:** NA

**Tutorials:** 06_calculating_returns, 07_functions, 08_calculating_option_payoff, 09_aggregation_grouping_part_1

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 03_stock_pnl

**Required Reading:** WTP 8, 11; PDSH 3.7-3.8, 3.12

**Supplemental Reading:** LOD 5.4 (in-progress); Python for Data Analysis (McKinney) - Chapter 9 (pp 251-274); Hull - Chapter 15 (pp 325-329)

&nbsp;


#### (05) 02/19 - `merge()`, `groupby()`, `agg()`


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** joining using the `.merge()` function, aggregation and grouping, working through a more complex analysis

**Slides:** NA

**Tutorials:** 10_joining_dataframes, 11_aggregation_grouping_part_2, 12_occ_volume_analysis

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 04_occ_volume, 05_iwm_vs_tna (start this, it's a bit tougher)

**Required Reading:** P4F 5.1 (two dimensional plotting - pp 109-128); PDSH 4.1-4.2

**Supplemental Reading:** P4F 6.1 (pandas basics - pp 137-151)


&nbsp;


#### (06) 02/26 - finance bootcamp


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** We cover, at a very high-level, the finance material that you will need to know for the remainder of the course.  This will be a very cursory treatment, and my intention is for you to be able to complete the project, even if you don't fully grasp all the finance.  We'll also discuss the project.

**Slides:** 04_finance_bootcamp

**Tutorials:** NA

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 05_iwm_vs_tna, choose groups and e-mail me your group members

**Required Reading:** NA

**Supplemental Reading:** LOD 2.1-2.3, 3.2-3.3, 5.1-5.5 

&nbsp;

#### (07) 03/05 - group projects assigned and visualziation


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** We'll discuss the group projects and start talking about data visualization.

**Slides:** NA

**Tutorials:** 13_line_graphs_with_pandas

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 06_option_pnl

**Required Reading:** PDSH 1.3, P4F 6.2 (financial data - pp 151-157)

**Supplemental Reading:** P4DA 8.1-8.2 (pp 219 - 241)

&nbsp;


#### (08) 03/12 - more visualization


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** Jupyter tips and tricks (keyboard shortcuts, restart and run all, restart and clear output, move selected cells up/down)

**Slides:** NA

**Tutorials:** 14_bar_charts_with_pandas, 15_scatter_plots_with_pandas, 16_visualization_with_seaborn

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** 07_spy_calls

**Required Reading:** PDSH 4.14 

**Supplemental Reading:** P4F 121-127 (other plot types); [Official Seaborn Tutorials](https://seaborn.pydata.org/tutorial.html)

&nbsp;


#### (09) 03/19 - spring break, no class

&nbsp;

#### (10) 03/26 - additional data analysis topics


<span style="color:gray":>*Material Covered:*</span> 

**Topics:** discuss the analysis project, `DataFrame.query()`, `DataFrame.eval()`, simulation

**Slides:** NA

**Tutorials:** 17_eval_query, 18_simulation

<span style="color:gray":>*Assignment:*</span> 

**Coding Exercise:** TBD

**Required Reading:** TBD 

**Supplemental Reading:** P4F pp 59-68 (Monte Carlo Simulation); P4F pp 468-470 (Random Generation)


